spring:
  application:
    name: ImposterAi

  datasource:
    url: jdbc:postgresql://localhost:5432/ImpostAi
    username: mox
    password: Moxtehlan@2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     ddl-auto: update

jwt:
  secretKey: bXkxNkFocUhKbTFxNUtpc2Y0NlNxRkJmRHo4b3B0TGFEcVpXZkpNTkRuVnF1YmFK