spring:
  application:
    name: ImposterAi

  datasource:
    url: ${DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      project-id: ${OPENAI_PROJECT_ID}
      chat:
        options:
          model: gpt-4o

game:
  matchmaking:
    bot-match-probability: 0.5
    max-wait-time-seconds: 30
    max-concurrent-matches: 1000
    bot-matching-enabled: true
    game-duration: 120

jwt:
  secretKey: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
